### ISSUE TITLE
After recent update, old wallpapers don't work anymore

### ISSUE THREAD

**Issue by jonibim** [zzag/plasma5-wallpapers-dynamic#100]
After the recent update, my entire library of .heic wallpaper which were converted using the tool provided in the README file, do not show any image anymore. They instead show the following error as an image

  ![image](https://user-images.githubusercontent.com/16855557/163454696-68a084b3-a26a-46fc-a5c1-7bd221f83be0.png)

Was the support for .heic files dropped? I noticed that the conversion tool defaults to .avif files? Is it possible to bring back support for __converted__ .heic files?

**Comment by zzag** [comment]
If you've built the wallpapers, run kdynamicwallperbuilder command again to get an avif file.

If you've used a script to convert Mac wallpapers, download the script (see the link in README) and run it again to get an avif file.

**Comment by zzag** [comment]
You can also rollback to v3 if you don't need new day/night mode https://aur.archlinux.org/packages/plasma5-wallpapers-dynamic#comment-860520
