### ISSUE TITLE
Plugin crash when selecting image

### ISSUE THREAD

**Issue by Talkys** [zzag/plasma5-wallpapers-dynamic#102]
When the latest release was the 3, I've set a HEIF wallpaper. But then I updated the program, tried to change the HEIF image to the AVIF one but now when I try to open the manager to select the wallpaper, it tries to read the HEIF image and crashes.

Then my wallpaper turns black (and on 4.0 the desktop just stoped working, needing a reset to default and a reboot)
The builder is working fine, but this issue just makes it impossible to use.

**Comment by Talkys** [comment]
I've managed to do a workaround. Install the latest 3.x from source, delete all the wallpapers from the selector and uninstall. Install the newer version and it will work.

**Comment by Talkys** [comment]
This issue can happen in both versions. I do not have the heic wallpaper anymore, but I have the source images.
![0](https://user-images.githubusercontent.com/49161064/164507216-eaf4e14e-5427-4cc5-b525-16f945723404.png)
![1](https://user-images.githubusercontent.com/49161064/164507221-73855634-2196-459a-a9bf-0b357bd99fd5.png)
![2](https://user-images.githubusercontent.com/49161064/164507225-cbb1b578-15d5-4cbf-b7b7-c772504f1838.png)
![3](https://user-images.githubusercontent.com/49161064/164507227-979b7d42-2e99-4e0d-a9bd-6b78fe18bd3d.png)
![4](https://user-images.githubusercontent.com/49161064/164507231-c1bc7ee3-1262-4bae-8ea9-83f97e560e4f.png)
![5](https://user-images.githubusercontent.com/49161064/164507234-be412d04-bfc2-4da1-8c3f-61456a3e14e5.png)
![6](https://user-images.githubusercontent.com/49161064/164507235-2de9137c-4103-4ecd-8f22-7da3388ca257.png)
![7](https://user-images.githubusercontent.com/49161064/164507240-49a73366-a5a8-4cb8-8beb-4681a1548acb.png)

I created the heic wallpaper in 3.3.9 then I updated the package to 4.0.0. Then as the wallpaper was not working anymore I waited for some updates then tried with the 4.3 but faced the same problem

**Comment by zzag** [comment]
Not all images have the same resolution, I'll make sure that preview code handles that corner case well, but I recommend to ensure that all images have the same size.

**Comment by zzag** [comment]
The crash should be fixed.

**Comment by Talkys** [comment]
You work fast, dude. Nice job!
