### ISSUE TITLE
Fresh build not accepted as wallpaper

### ISSUE THREAD

**Issue by Talkys** [zzag/plasma5-wallpapers-dynamic#103]
Builder working fine, but selector do not accept the avif file.
Command works fine
![1](https://user-images.githubusercontent.com/49161064/164491048-78a0cff9-d46f-4073-a875-5c0296b09960.png)
The file is here
![2](https://user-images.githubusercontent.com/49161064/164491051-1b9dbee6-70d6-4a3c-984e-a9bc9f5c01b2.png)
But I can't set it
![3](https://user-images.githubusercontent.com/49161064/164491055-81457edd-1220-43e5-b970-9aac8830124c.png)

**Comment by zzag** [comment]
Can you show the contents of `set.json` file?

**Comment by Talkys** [comment]
> Can you show the contents of `set.json` file?

`{
  "Type": "solar",
  "Meta": [
    {
      "CrossFade": true,
      "Time": "00:00",
      "FileName": "0.png"
    },
    {
      "CrossFade": true,
      "Time": "03:00",
      "FileName": "1.png"
    },
    {
      "CrossFade": true,
      "Time": "05:30",
      "FileName": "2.png"
    },
    {
      "CrossFade": true,
      "Time": "06:30",
      "FileName": "3.png"
    },
    {
      "CrossFade": true,
      "Time": "10:00",
      "FileName": "4.png"
    },
    {
      "CrossFade": true,
      "Time": "14:00",
      "FileName": "5.png"
    },
    {
      "CrossFade": true,
      "Time": "18:00",
      "FileName": "6.png"
    },
    {
      "CrossFade": true,
      "Time": "19:00",
      "FileName": "7.png"
    }
  ]
}
`

**Comment by Talkys** [comment]
Github messed up with indentation, but I just copy pasted the read me layout.

**Comment by zzag** [comment]
With the latest changes, kdynamicwallpaperbuilder will fail to create the avif file if libavif doesn't like source images.

**Comment by zzag** [comment]
The issue is that there's an image of size 2344x1310 while other are of size 2340x1320.
