### ISSUE TITLE
Latest package updates causing issues

### ISSUE THREAD

**Issue by Rand-o** [zzag/plasma5-wallpapers-dynamic#105]
Updated these packages yday and caused the plugin to stop working. 
Options were removed from the GUI and my background just turned black.
Rolled back the updates and the plugin would work fine again.
I'm on arch btw.

Following had to be rolled back to these versions:
ffmpeg-2:5.0-6-x86_64.pkg.tar.zst
ffmpeg4.4-4.4.1-4-x86_64.pkg.tar.zst
dav1d-0.9.2-1-x86_64.pkg.tar.zst
libavif-0.9.3-1-x86_64.pkg.tar.zst
libyuv-r2266+eb6e7bb6-1-x86_64.pkg.tar.zst

**Comment by zzag** [comment]
Huh, so it wasn't just a hiccup on my machine, it looks like there was an abi incompatible change in libavif... :| Can you try rebuilding the package, it helped me to get the plugin work again? If you use yay make sure that the cache is purged.
