### ISSUE TITLE
openSuSE support and dependencies

### ISSUE THREAD

**Issue by romanyacik** [zzag/plasma5-wallpapers-dynamic#108]
This is probably more of a dependency issue than anything, but I cannot build this on openSuSE Tumbleweed. Error messages point to missing items related to KF5

-- Could NOT find KF5Config (missing: KF5Config_DIR)
-- Could NOT find KF5Config: found neither KF5ConfigConfig.cmake nor kf5config-config.cmake 
-- Could NOT find KF5I18n (missing: KF5I18n_DIR)
-- Could NOT find KF5I18n: found neither KF5I18nConfig.cmake nor kf5i18n-config.cmake 
-- Could NOT find KF5Package (missing: KF5Package_DIR)
-- Could NOT find KF5Package: found neither KF5PackageConfig.cmake nor kf5package-config.cmake 
-- Could NOT find KF5Plasma (missing: KF5Plasma_DIR)
-- Could NOT find KF5Plasma: found neither KF5PlasmaConfig.cmake nor kf5plasma-config.cmake

**Comment by zzag** [comment]
It looks like you need to install some build dependencies. https://github.com/zzag/plasma5-wallpapers-dynamic#building-from-git lists build dependencies for Ubuntu, Fedora, and Arch. The package names for Fedora and openSUSE should be similar, I'm not an openSUSE user though so take my words with a grain of salt. If you manage to resolve the build dep issue, can you list the package name that you had to install so I could put them in the README.md file?

**Comment by zzag** [comment]
Closing the issue as I am unfamiliar with what packages need to be installed on openSUSE. If you resolve the issue, please still post here the list of packages that you installed so I can put them in README
