### ISSUE TITLE
"Encoding of color planes failed"

### ISSUE THREAD

**Issue by Pistrie** [zzag/plasma5-wallpapers-dynamic#113]
When I try to encode the [default.jpg image from the CutefishOS wallpapers](https://github.com/cutefishos/wallpapers/blob/main/sources/default.jpg) I get the following error:
~~~
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
"Failed to encode /home/sylvester/Pictures/wallpapers/linux/cutefish-wallpapers/default.jpg: Encoding of color planes failed"
~~~

My `manifest.json`:
```json
{
  "Type": "day-night",
  "Meta": [
    {
      "TimeOfDay": "day",
      "FileName": "/home/sylvester/Pictures/wallpapers/dtos-backgrounds-main/0240.jpg"
    }, {
      "TimeOfDay": "night",
      "FileName": "/home/sylvester/Pictures/wallpapers/linux/cutefish-wallpapers/default.jpg"
    }
  ]
}
```

**Comment by zzag** [comment]
Are the images of the same size?

**Comment by Pistrie** [comment]
They are not. I'm guessing that's the problem

**Comment by zzag** [comment]
> Edit: Yup, resizing with gimp did the trick. Might I suggest you add this info to the readme? :)

I'll make kdynamicwallpaperbuilder print a more helpful message rather than simply forward whatever error message libavif provides us.
