### ISSUE TITLE
Failed to encode image, no codec available

### ISSUE THREAD

**Issue by Hatrian** [zzag/plasma5-wallpapers-dynamic#115]
I'm trying to use kdynamicwallpaperbuilder to make my own dynamic wallpaper but when I run the command it tells me "Failed to encode [my image path]: No codec available". I'm assuming it's because my linux install (KDE Neon) doesn't support avif out of the box, but I'm not sure how to find/install a codec that would make this work.

**Comment by zzag** [comment]
Do you have `rav1e` installed?

**Comment by Hatrian** [comment]
I just installed it (I think?) and still have the same issue.

**Comment by jannesblm** [comment]
Same problem on Void Linux; I manually compiled libavif and enabled rav1e (e.g. AVIF_CODEC_RAV1E). Newer versions of libavif seem to  require a third parameter for the functions avifImageYUVToRGB(p1, p2, AVIF_YUV_TO_RGB_DEFAULT) (and vice versa) in kdynamicwallpaperreader/writer.cpp, relinked and kdynamicwallpaperbuilder worked as intended.

**Comment by zzag** [comment]
> Newer versions of libavif seem to require a third parameter for the functions avifImageYUVToRGB(p1, p2, AVIF_YUV_TO_RGB_DEFAULT) 

Huh what version is that? On my machine with libavif 0.11, I see no such third parameter in avifImageYUVToRGB or avifImageRGBToYUV

**Comment by jannesblm** [comment]
> Huh what version is that?

Apologies, seems like I was using a development version then. There were some API changes which have since been reverted. So it should theoretically work fine without any changes when manually compiling.

**Comment by zzag** [comment]
Phew! @Hatrian did you use development version too?

**Comment by zzag** [comment]
dup of #114
