### ISSUE TITLE
Wrong images when `SolarAzimuth` and `SolarElevation` are given

### ISSUE THREAD

**Issue by SebinNyshkim** [zzag/plasma5-wallpapers-dynamic#116]
Hi,

I'm using https://keisan.casio.com/exec/system/1224682277 to generate `SolarAzimuth` and `SolarElevation` values for my custom dynamic wallpaper. But for some reason, if I include these values the wrong image gets picked for the time of day I would expect. Only using `Time` picks the expected image as configured in the metadata JSON file.

Given the time of day of `19:00`, an elevation of `34.88` and an azimuth of `139.05` I would expect [this image](https://gitlab.com/SebinNyshkim/sebin-dynamic-wallpaper/-/blob/main/sebin-dynamic-1700.png) to be displayed.

But when picking wallpaper type "Dynamic" and setting it to the generated `.avif` file, [this image](https://gitlab.com/SebinNyshkim/sebin-dynamic-wallpaper/-/blob/main/sebin-dynamic-2300.png) gets displayed.

I'm puzzled whether this is a bug in the wallpaper plugin or I'm passing it wrong `SolarAzimuth` and `SolarElevation` values.

**Comment by SebinNyshkim** [comment]
It seems like I forgot to adjust the time zone value on the casio website which resulted in wrong values being output by the calculator. Setting the time zone to my actual time zone the correct image now gets displayed when including `SolarAzimuth` and `SolarElevation` values.

That's what I get for doing this stuff at 04:00 in the morning...

Case closed 🙃

**Comment by zzag** [comment]
Glad that the issue has been solved. In general, it would be nice to write a tool that computes the sun timings for you, i.e. #62, it would make creating dynamic wallpapers a lot easier. But I don't have time to actually start working on it.
