### ISSUE TITLE
Convert does not work

### ISSUE THREAD

**Issue by Retch** [zzag/plasma5-wallpapers-dynamic#119]
Wanted to convert a .heic, where is a .avif file created but with size 0 and there is no more output.

![image](https://user-images.githubusercontent.com/16291785/194857098-6ff7a9ba-0829-4696-ae40-671fba21d015.png)

**Comment by pavel-the-best** [comment]
Eh it does work it just needs a couple of CPU-days to process the image. Slap it onto a 64-thread machine and you'll be fine (-ish, it still takes about 15 minutes). :)

**Comment by zzag** [comment]
Added `--speed` option, check README.md
