### ISSUE TITLE
Arch Linux KDE Plasma: Unable to run kdynamicwallpaperbuilder due to not implemented error

### ISSUE THREAD

**Issue by Borflux** [zzag/plasma5-wallpapers-dynamic#121]
I am running arch linux using kde plasma and have been attempting to create my dynamic wallpaper using the kdynamicwallpaperbuilder command line tool by following the instructions specified in the README. Unfortunately when I try to run kdynamicwallpaperbuilder: 
`kdynamicwallpaperbuilder --output wallpaper.avif manifest.json`

I recieve the following output: 
`"Failed to encode [filename].jpg: Not implemented"`

[filename].jpg is always the first filename in my manifest file. I have tried building with absolute paths and relative paths from my manifest file but the result is the same regardless.

From my searches online I've found that this is an error thrown from libavif which can be found in the avifResultToString method in avif.c in libavif's source code. Unfortunately I wasn't able to find anymore specific information than that regarding this error.

I've tried troubleshooting this issue using the following ideas which I've found here on other issues and elsewhere on the internet:
- Compiling plasma-wallpapers-dynamic from source
- Compiling libavif from source with rav1e enabled and rebuilding plasma5-wallpapers-dynamic from source and using an aurhelper (pikaur)
- Converting images into the .png format using ImageMagick and updating my manifest.json file
- Converting images into the .avif format using ImageMagick and updating my manifest.json file
-  Changing the manifest.json file to use the night/day settings with two images instead of setting specific times for all of my images that I'd like to add

When I build plasma5-wallpapers-dynamic either from source or using pikaur I do recieve a message stating that the following RUNTIME packages have not been found:
` * QtQuick.Controls-QMLModule, QML module 'QtQuick.Controls' is a runtime dependency.`
 `* QtQuick.Dialogs-QMLModule, QML module 'QtQuick.Dialogs' is a runtime dependency.`
 `* org.kde.kcm-QMLModule, QML module 'org.kde.kcm' is a runtime dependency.`
`* org.kde.kirigami-QMLModule, QML module 'org.kde.kirigami' is a runtime dependency.`
I am still able to see Wallpaper type: Dynamic in my plasma settings window though regardless of these build warning messages.

Regardless of what I've tried I cannot seem to get past this error. Any help with this would be greatly appreciated.

**Comment by NunonuN** [comment]
I have the same problem. Manjaro KDE, latest Plasma version (5.26.3).

**Comment by zzag** [comment]
> Failed to encode [filename].jpg: Not implemented

Perhaps it's related to https://github.com/zzag/plasma5-wallpapers-dynamic/issues/115#issuecomment-1238523874

> When I build plasma5-wallpapers-dynamic either from source or using pikaur I do recieve a message stating that the following RUNTIME packages have not been found:

You can ignore these.

**Comment by Borflux** [comment]
> Perhaps it's related to [#115 (comment)](https://github.com/zzag/plasma5-wallpapers-dynamic/issues/115#issuecomment-1238523874)

I took a look at libavif again to see if I was having any of the compatibility issues with my version of libavif that were mentioned in #115 but I haven't found anything to indicate that my libavif avifImageYUVToRGB method contains a third parameter. I also checked the version of libavif that I am currently running and it appears to be version 0.11.1-1 according to pacman. 

Pacman also indicates libavif is dependent upon rav1e so I don't think there is a direct issue there.

**Comment by zzag** [comment]
Weird. Can you check that all images have the same size?

**Comment by Borflux** [comment]
> Weird. Can you check that all images have the same size?

That worked for me. I used image magick to resize all of my wallpaper images to the same size and I didn't run into the "Not Implemented" error anymore. 

Thanks for your help!

**Comment by zzag** [comment]
dup of #114
