### ISSUE TITLE
failed to encode: my image is not implemented

### ISSUE THREAD

**Issue by lolzhunter** [zzag/plasma5-wallpapers-dynamic#126]
Making this because I'm not exactly sure whats tripping me up here, I'm a manjaro linux KDE plasma user and I'm using 3 images in a solar cycle, 2 of the images get by no problem it's just this one image set at for 12 midday that just won't cooperate.

here's my entire json file:

![image](https://github.com/zzag/plasma5-wallpapers-dynamic/assets/51302861/37d5e337-dcee-49de-a129-fff0091530b2)

and here's what I'm getting consistently:
![image](https://github.com/zzag/plasma5-wallpapers-dynamic/assets/51302861/0d027051-df4a-4278-8c07-25aafaf82be2)

I have tried resizing the image and saving it, changing crossfade, changing the name, setting the time 1 min ahead nothing worked.

I would like to note the file size is 2.6mb but the other two working images have 2.2mb and 1.2mb so i don't think its to do with that.

Any help would seriously be appreciated I'm stuck on what to do here, its honestly quite frustrating that there isn't much out there for changing wallpapers like this

**Comment by zzag** [comment]
The error message likely comes from `avifEncoderAddImage()`. Do jpg images have the same resolution?

**Comment by lolzhunter** [comment]
all 3 images have different sizes

**Comment by zzag** [comment]
That's likely the reason. I'll add a more user-friendly error message instead of using whatever libavif spits out when `avifEncoderAddImage()` fails.

**Comment by lolzhunter** [comment]
ill give that a go, they only slightly differ, course the other way to fix it would be to zoom in the image automatically until all images are same size

**Comment by lolzhunter** [comment]
ok it encoded but when i equip it as a wallpaper its just cycling through the images, doesnt care about timing

**Comment by lolzhunter** [comment]
yep all good works now, thanks for helping i appreciate it a ton
