### ISSUE TITLE
new plasma update broke the wallpaper for me (manjaro)

### ISSUE THREAD

**Issue by lolzhunter** [zzag/plasma5-wallpapers-dynamic#129]
yeah its just a black background now when i set it to dynamic :/

![image](https://github.com/zzag/plasma5-wallpapers-dynamic/assets/51302861/7641c52f-c761-4e6e-a67b-3c0da6d51013)
![image](https://github.com/zzag/plasma5-wallpapers-dynamic/assets/51302861/6515df27-1028-4f44-8e37-26447a00a992)

**Comment by zzag** [comment]
Hmm.. Can you try reinstalling the wallpaper? Make sure that the wallpaper is rebuilt, e.g. by clearing yay cache

**Comment by lolzhunter** [comment]
yep that fixed it, thanks, in retrospect should have tried that first mb
![image](https://github.com/zzag/plasma5-wallpapers-dynamic/assets/51302861/d28489c2-2a29-44f0-82a1-1b400f307bcf)
