### ISSUE TITLE
kdynamicwallpaperbuilder: GPS Data not recognized

### ISSUE THREAD

**Issue by OWL4C** [zzag/plasma5-wallpapers-dynamic#136]
When using `"*"` for the Solar Metadata kdynamicwallpaperbuilder returns `Failed to compute the position of the Sun based on GPS coordinates and the time when the photo was taken. Please check that the specified image actually has GPS coordinates in its Exif metadata. You can do that with a tool such as exiftool.`
I have this error with both my actual dataset as well as a test file, which is attached. In case the exif gets stripped by github, i have set `-GPSLongitudeRef=E -GPSLatitudeRef=N -GPSLatitude=0.0 -GPSLongitude=0.0` manually with exiftool and it shows working when looking at the file with exiftool again, as well as the normal File Explorer Exif Info.
![chinese-reed-8493547_1280](https://github.com/zzag/plasma5-wallpapers-dynamic/assets/124401812/abba3df7-5c41-46ed-96de-40044d354cc9) 

The picture is from https://pixabay.com/photos/chinese-reed-reed-grass-plant-8493547/

**Comment by zzag** [comment]
Hmm it looks like DateTimeOriginal or GPSTimeStamp+GPSDateStamp are missing. They are needed to figure out _when_ the picture was taken to compute the position of the Sun. Both location and time are needed for that

**Comment by zzag** [comment]
I will improve the error message. Is it possible to get exiftool dump for one of the images (please redact sensitive information such as location)?

**Comment by OWL4C** [comment]
Ok, thinking about it makes it seem pretty stupid. I definitely miss the GPS Timestamp tags since i added the Location Tags manually, since my camera doesn't have the functionality
It would be really good to have more info about which tags are required in either/and the error or the README.

**Comment by zzag** [comment]
> It would be really good to have more info

Yeah, I'll update the error messages and update README. Thanks!
