### ISSUE TITLE
Support for KDE 6

### ISSUE THREAD

**Issue by Cediddi** [zzag/plasma5-wallpapers-dynamic#137]
Hi, with the release of KDE6, do you plan to port this project to it?

Only one plugin so far has ported: and this is how they did it: https://github.com/easyteacher/plasma-wallpaper-random-color/commit/27fe540bb5917222d9298a8251a08ead990d41a1

**Comment by zzag** [comment]
It's already ported to Plasma 6

**Comment by Cediddi** [comment]
I think the readme does not imply that, nor the updated dependencies for Ubuntu. I cannot compile the project under kde neon, probably some packages are not released yet.

```
Unable to locate package qtbase6-dev
Unable to locate package qtdeclarative6-dev
Unable to locate package qtpositioning6-dev
Unable to locate package qtdeclarative6-private-dev
Unable to locate package qtbase6-private-dev
```

Thank you for the porting, I'll try again in the next weeks.

**Comment by SlimRG** [comment]
> I think the readme does not imply that, nor the updated dependencies for Ubuntu. I cannot compile the project under kde neon, probably some packages are not released yet.
> 
> ```
> Unable to locate package qtbase6-dev
> Unable to locate package qtdeclarative6-dev
> Unable to locate package qtpositioning6-dev
> Unable to locate package qtdeclarative6-private-dev
> Unable to locate package qtbase6-private-dev
> ```
> 
> Thank you for the porting, I'll try again in the next weeks.

Now Plasma 6 in Release.

Maybe smth changes?)

**Comment by Cediddi** [comment]
I think KDE Neon only released those packages to Unstable channel. 

```bash
$ sudo apt install cmake extra-cmake-modules git libkf6package-dev libkf6plasma-dev libkf6i18n-dev qtbase6-dev qtdeclarative6-dev qtpositioning6-dev gettext qml-module-qtpositioning libexif-dev libavif-dev build-essential qtdeclarative6-private-dev qtbase6-private-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package qtbase6-dev
E: Unable to locate package qtdeclarative6-dev
E: Unable to locate package qtpositioning6-dev
E: Unable to locate package qtdeclarative6-private-dev
E: Unable to locate package qtbase6-private-dev
```
