### ISSUE TITLE
Document that KPlugin.id in metadata.json must be identical to wallpaper's folder name

### ISSUE THREAD

**Issue by Schlaefer** [zzag/plasma5-wallpapers-dynamic#17]
Updating to 2.0 it says "Unique id" in the metadata sample, so i just threw something in. But no wallpaper showed up. That one took me a while. :wink:

**Comment by zzag** [comment]
Yeah, I got a bit lazy on this one. kpackagetool5 ensures that KPlugin Id field matches wallpaper's folder name in ${DATADIR}/dynamicwallpapers so I didn't bother emphasizing this little nuance.

Perhaps it will be better to write a more detailed overview of metadata.json file.

**Comment by zzag** [comment]
> kpackagetool5 ensures that KPlugin Id field matches

FYI, I extended the config module a bit so one can install/uninstall a dynamic wallpaper without opening terminal. You just have to point the config to metadata.json file and it will do the rest for you, renaming wallpaper's folder is one of those things.

![Screenshot_20191018_194007](https://user-images.githubusercontent.com/19847234/67112547-28251d00-f1e0-11e9-864c-3ab7ff82a56f.png)

**Comment by Schlaefer** [comment]
I'm not sure how this works without seeing it in action. If the automagic is intuitive: great. Otherwise just pointing out in the documentation:

1. You put your theme folders *here* (the `shared/dynamicwallpaper`) 
2. Here's how the folder structure looks like
3. Here's how you set up the metadata.json
4. Make sure that the `id` matches your theme folder name

would be fine for me. I assume that a user has to dive into the documentation for 2 and 3 anyway?

**Comment by zzag** [comment]
No, ordinary users don't need to know how exactly a dynamic wallpaper is laid out. The best scenario: the user can install a wallpaper off the Internet (store.kde.org). However, I don't think it's possible at the moment because the ecosystem around this plugin is weak, there are not that many dynamic wallpapers. :(

> Otherwise just pointing out in the documentation:

I have to write the documentation in either case, it's just me being lazy. :/

**Comment by Schlaefer** [comment]
> No, ordinary users don't need to know how exactly dynamic wallpapers are laid out. The best scenario: the user can install a wallpaper off the Internet (store.kde.org).

That would of course be great. 

> However, I don't think it's possible at the moment because the ecosystem around this plugin is weak, there are not that many dynamic wallpapers. :( 

We had a similar discussion over there at #9. Imho there are great wallpapers, but easy compatibility would require a more serious organizational and time commitment than "just" providing code. I'm absolutetly grateful for the code alone, I rather have that than a "I can't pour time into supporting a complete and easy to use ecosystem, so lets give up on both". But that's a decision only you can make.

> I have to write the documentation in either case, it's just me being lazy. :/

From my end-user point of view you have everything else down. :+1:  Just the OP nugget of information was missing.

**Comment by zzag** [comment]
Hey, so I've updated README.md file and added a couple of useful Wiki pages. However, I didn't mention that the Id key must match wallpaper's folder name since the preferred way for installing new dynamic wallpapers is to use "Add Wallpaper..." button.

If you're happy with the documentation, I'll close this issue.

**Comment by zzag** [comment]
Also, if you have suggestions, I'll be happy to review and merge MR(s). ;-)

**Comment by zzag** [comment]
I'll close this issue in a few days due to the lack of activity.

**Comment by Schlaefer** [comment]
Sorry, I hadn't time to check it out. Just close it, I'm sure it's fine. I'll try to test the Add Wallpaper button over the weekend and add thoughts if there are any.

**Comment by Schlaefer** [comment]
OK. The Add Wallpaper buttons works great. I also tested the importer, really nice! :+1:
