### ISSUE TITLE
Problem Importing .heic dynamic wallpapers

### ISSUE THREAD

**Issue by Sobuj53** [zzag/plasma5-wallpapers-dynamic#27]
Hello,
I've installed dynamic-wallpaper-importer plugin and now trying to import .heic file but after importing dynamic wallpaper via dynamic-wallpaper-importer tool when ever I try to install with kpackagetool5 it says "Error: Installation of  failed: No such file:"

My system is: KDE Neon (Ubuntu 18.04 LTS)
please see the attached file for more information.
![error](https://user-images.githubusercontent.com/25761237/68267076-54171e00-007b-11ea-84f7-7ed8a6de6d30.png)

the Firewatch.heic file is located in /home/<username>/Downloads/ so is my current directory in terminal that's why I didn't type the source path but I've also tried with the path but it's same, doesn't work.
I'd really appreciate your help on this.
Thank you.

**Comment by zzag** [comment]
Could you please rebuild `dynamic-wallpaper-importer` tool with https://github.com/zzag/dynamic-wallpaper-importer/commit/2446da7edf63879c49b4baeb9e98f43036caf567 included?

**Comment by Sobuj53** [comment]
Hi @zzag 
Thank you for your reply. I've rebuild  `dynamic-wallpaper-importer ` from your mentioned link, still same error. Please see the attached file for more info.
Latest importer,
![latest](https://user-images.githubusercontent.com/25761237/68289402-39ab6780-00b0-11ea-84de-f8723b6bb5fb.png)
Error
![error](https://user-images.githubusercontent.com/25761237/68289433-4d56ce00-00b0-11ea-9da3-5cba9dfd7fb5.png)

**Comment by Sobuj53** [comment]
Thank you. It works now!
