### ISSUE TITLE
Missing "org.kde.kirigami" version 2.10

### ISSUE THREAD

**Issue by canejj** [zzag/plasma5-wallpapers-dynamic#30]
Hi,

I installed your app and I see the option "Dynamic" in the "Configure Desktop" dialog of Plasma5, but then when I select it, I get the error message in the attachments and nothing works. Any idea of why? I know "org.kde.kirigami" to be installed and I am on Debian 10, Linux MX 19 distro, with the KDE Plasma 5 desktop environment installed.

Moreover is there any way to run your applet through the terminal somehow? Because I didn't find any proper way, yet...

Thanks in advance!

![Screenshot](https://user-images.githubusercontent.com/60240078/73025163-5f364a80-3e2f-11ea-9c30-f2defcc99ebb.png)

**Comment by zzag** [comment]
What version of Kirigami do you have on your system?

> Moreover is there any way to run your applet through the terminal somehow?

Nope, the idea was that you select "Dynamic" from the combobox and after that everything "just works."

**Comment by zzag** [comment]
Can you please test 53a4b3a?

**Comment by canejj** [comment]
Now, it works in that it doesn't show any error message anymore.

Thanks for fixing that up!

However, it doesn't seems to be able to show any wallpaper... all what I ever get is a pitch black background...

**Comment by zzag** [comment]
Could you provide a screenshot?

**Comment by canejj** [comment]
With what exactly? Everything's just pitch black... and for the configuration, I just kept it default.



![Screenshot-1](https://user-images.githubusercontent.com/60240078/73121586-dd076c80-3f7b-11ea-96f2-7558eda56769.png)

**Comment by zzag** [comment]
Hmm, this is odd... The default wallpaper doesn't have a preview image. You should see something like this

![Screenshot_20200125_151340](https://user-images.githubusercontent.com/19847234/73121706-9159c080-3f85-11ea-90a5-3e2c6443661a.png)

Could you please run `plasmashell --replace` from command line and post its output here?

**Comment by zzag** [comment]
Heh, I overlooked one `import`. Could you please test e91df19?

**Comment by canejj** [comment]
Sure, plasmashell says:

`Icon theme "elementary" not found.
Aborting shell load: The activity manager daemon (kactivitymanagerd) is not running.
If this Plasma has been installed into a custom prefix, verify that its D-Bus services dir is known to the system for the daemon to be activatable.
org.kde.plasmaquick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:62:28: Unable to assign [undefined] to int
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:53:27: Unable to assign [undefined] to int
"file:///usr/share/plasma/wallpapers/com.github.zzag.wallpaper/contents/ui/main.qml" 
 "Error loading QML file.\n43: Type WallpaperView unavailable\n128: Expected token:
trying to show an empty dialog
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
trying to show an empty dialog
trying to show an empty dialog
Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
Plasma Shell startup completed
org.kde.plasmaquick: New Applet  "Application Launcher" with a weight of 92
org.kde.plasmaquick: New Applet  "Digital Clock" with a weight of 0
Both point size and pixel size set. Using pixel size.
trying to show an empty dialog
org.kde.plasmaquick: New Applet  "Audio Volume" with a weight of 4
org.kde.plasmaquick: New Applet  "Clipboard" with a weight of 0
org.kde.plasmaquick: New Applet  "Device Notifier" with a weight of 0
org.kde.plasmaquick: New Applet  "KDE Connect" with a weight of 0
org.kde.plasmaquick: New Applet  "Keyboard Indicator" with a weight of 0
org.kde.plasmaquick: New Applet  "Notifications" with a weight of 0
org.kde.plasmaquick: New Applet  "Updates" with a weight of 0
org.kde.plasmaquick: New Applet  "Networks" with a weight of 0
org.kde.plasmaquick: New Applet  "Bluetooth" with a weight of 0
org.kde.plasmaquick: New Applet  "Battery and Brightness" with a weight of 0
Icon theme "elementary" not found.
Icon theme "elementary" not found.
org.kde.plasmaquick: Delayed preload of  "Application Launcher" after 0.356 seconds
KAStatsFavoritesModel::setFavorites is ignored
KActivities: Database connection:  "kactivities_db_resources_139729936525376_readonly" 
    query_only:          QVariant(qlonglong, 1) 
    journal_mode:        QVariant(QString, "wal") 
    wal_autocheckpoint:  QVariant(qlonglong, 100) 
    synchronous:         QVariant(qlonglong, 0)
Entry is not valid "kontact.desktop" 0x558adf66c050
Entry is not valid "ktp-contactlist.desktop" 0x558adf66c050
Entry is not valid "kontact.desktop" 0x558adf66c050
Entry is not valid "ktp-contactlist.desktop" 0x558adf66c050
Closing SQL connection:  "kactivities_db_resources_139729936525376_readonly"
trying to show an empty dialog
org.kde.plasmaquick: Applet "Application Launcher" loaded after 96 msec
org.kde.bluez: GetManagerJob Error: "Cannot find org.bluez.Media1 object!"
couldn't understand value for timer: ""
using... PackageKit::Transaction(0x558adf31a4c0) "/198_baccadee"`

**Comment by canejj** [comment]
I tested again and now it looks like this:
![Screenshot-2](https://user-images.githubusercontent.com/60240078/73126500-b06f4700-3fb3-11ea-8567-595db2cff68a.png)
I can see the default picture being shown in the dialog, but not set as wallpaper.. which still pitch black.

**Comment by canejj** [comment]
Addionally when I launch plasmashell and I activate the dialog to select your wallpaper changer, I get this: 
**`file:///usr/share/plasma/wallpapers/com.github.zzag.wallpaper/contents/ui/config.qml:46: ReferenceError: parentLayout is not defined
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls.2/org.kde.desktop/ComboBox.qml:137:29: Unable to assign [undefined] to QQmlComponent*
file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls.2/org.kde.desktop/ToolTip.qml:45: TypeError: Cannot read property 'hovered' of null
"file:///usr/share/plasma/wallpapers/com.github.zzag.wallpaper/contents/ui/main.qml" 
 "Error loading QML file.\n43: Type WallpaperView unavailable\n128: Expected token :'\n"
`**

**Comment by zzag** [comment]
> "Error loading QML file.\n43: Type WallpaperView unavailable\n128: Expected token :'\n"

What version of Qt do you have installed on your system? (please say it's >= 5.12)

> file:///usr/share/plasma/wallpapers/com.github.zzag.wallpaper/contents/ui/config.qml:46: ReferenceError: parentLayout is not defined

Urgh, that's what I was afraid of.

**Comment by zzag** [comment]
Could you please test b926c96? I think everything should work now (well, except parentLayout thing).

**Comment by canejj** [comment]
Yes, now it seems to be working accordingly! 

Thing is I would need to use the .json file with the time change and not the longitude & latitude.. 

Is there a better way to do that other than having to count all the seconds since the start of the day and divide that by 86400, which is admittedly not the most natural way to think?

**Comment by zzag** [comment]
You could use a Python script for that purpose

```python
#!/usr/bin/env python3

import argparse

from dateutil import parser as datetime_parser


argument_parser = argparse.ArgumentParser()
argument_parser.add_argument('input', type=str)
arguments = argument_parser.parse_args()

datetime = datetime_parser.parse(arguments.input)
midnight = datetime.replace(hour=0, minute=0, second=0, microsecond=0)

print((datetime - midnight).total_seconds() / 86400)
```

Example usage

```
~
❯ chmod +x convert-time.py 

~
❯ ./convert-time.py '10:44 AM'
0.44722222222222224

~
❯ ./convert-time.py '10:44 PM'
0.9472222222222222
```

**Comment by zzag** [comment]
Alternatively, you could use https://dynamicwallpaper.club/ to create a heic dynamic wallpaper and then use `dynamic-wallpaper-importer`.

**Comment by zzag** [comment]
> and not the longitude & latitude..

Small correction: with "solar" dynamic wallpapers, you have to provide position of the Sun, which is elevation + azimuth. ;-)
