### ISSUE TITLE
QtQuick.Dialogs Error

### ISSUE THREAD

**Issue by lucaspar** [zzag/plasma5-wallpapers-dynamic#31]
After following the installation instructions, including installing all libraries required, I still get this error when trying to enable the Dynamic Wallpapers in Plasma 5

```
System Specs:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

plasmashell 5.12.9
```

![Error screenshot](https://user-images.githubusercontent.com/7535699/74597979-c2825980-5036-11ea-9524-a894fbe32a70.png)

**Comment by zzag** [comment]
Could you please test 8314a72?

**Comment by lucaspar** [comment]
After getting the changes I had a similar error with `QtQuick.Controls 2.3`, which I downgraded to `2.1`. Then the same happened with `org.kde.kirigami 2.5`, which I downgraded to `2.3` and got the message below:

![img](https://user-images.githubusercontent.com/7535699/74611373-3a995f80-50c9-11ea-90ea-d7a0ebc9ab4b.png)

**Comment by zzag** [comment]
Urgh, perhaps I should just bump the minimum version for KF and Qt...

Anyway, you could try to comment out

https://github.com/zzag/plasma5-wallpapers-dynamic/blob/master/src/package/contents/ui/config.qml#L131-L140

 https://github.com/zzag/plasma5-wallpapers-dynamic/blob/master/src/package/contents/ui/config.qml#L236

or you could just install kirigami >= 5.45.

**Comment by lucaspar** [comment]
Yeah, no luck commenting those lines.
I guess upgrading the versions would be the way to go, but I'll wait until I upgrade my distro. Thanks!

**Comment by zzag** [comment]
@lucaspar Any updates?

**Comment by sillydan1** [comment]
I get the error message for org.kde.kirigami as well

![Screenshot_2020-03-21_22-30-58](https://user-images.githubusercontent.com/4085393/77236990-1ea34500-6bc4-11ea-8c59-a5e4a1859144.png)

`System specs:
Debian 10
Kernal: x86_64 Linux 4.19.0.8-am64
Plasma: 5.14.5
`

**Comment by zzag** [comment]
@sillydan1 Debian ships sort of old KF. You need to install KF >= 5.58 to get rid of the error message.

**Comment by zzag** [comment]
Closing this issue due to the lack of activity.
