### ISSUE TITLE
Not working on Manjaro

### ISSUE THREAD

**Issue by TheJSHuA** [zzag/plasma5-wallpapers-dynamic#33]
When I try to use this with Manjaro (installed through AUR) it doesn't work. The dynamic wallpaper option appears, however there's no options under it and it throws an error: 
`
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationContainmentAppearance.qml:166:5: QML StackView: replace: file:///usr/share/plasma/wallpapers/com.github.zzag.wallpaper/contents/ui/config.qml:17 module "com.github.zzag.private.wallpaper" is not installed`

**Comment by zzag** [comment]
It might be a Qt version mismatch issue or something. Have you tried reinstalling the plugin?

**Comment by TheJSHuA** [comment]
I've tried reinstalling and it doesn't fix it. However, when I install in the AUR, it throws an error the first time it tries to build, but if you retry the build again it doesn't happen. That might have something to do with it.

**Comment by zzag** [comment]
Are you using yay? If so, please clear cache.

**Comment by TheJSHuA** [comment]
I'm using trizen, but I cleared cache anyway just to make sure (`trizen -Scc`) and reinstalled. Same build error persists but disappears if you build it a 2nd time

This is the build error:
```
In file included from /usr/include/qt/QtGui/QGuiApplication:1,
                 from /tmp/trizen-josh/plasma5-wallpapers-dynamic/src/plasma5-wallpapers-dynamic-2.7/src/declarative/dynamicwallpaperpreviewprovider.cpp:11:
/usr/include/qt/QtGui/qguiapplication.h:159:57: error: ‘Qt::HighDpiScaleFactorRoundingPolicy’ has not been declared
  159 |     static void setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy policy);
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/qt/QtGui/qguiapplication.h:160:16: error: ‘HighDpiScaleFactorRoundingPolicy’ in namespace ‘Qt’ does not name a type
  160 |     static Qt::HighDpiScaleFactorRoundingPolicy highDpiScaleFactorRoundingPolicy();
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by zzag** [comment]
What version of Qt is installed on your computer? Also, what compiler do you use?

**Comment by zzag** [comment]
> error: ‘Qt::HighDpiScaleFactorRoundingPolicy’ has not been declared

The HighDpiScalleFactorRoundingPolicy enum is defined in QtCore/qnamespace.h, but qguiapplication.h includes it indirectly.

**Comment by TheJSHuA** [comment]
I'm running qt 5.14.1, and using gcc

**Comment by zzag** [comment]
Hmm, interesting... Have you tried building the plugin from source code? See README.md
