### ISSUE TITLE
Wallpaper ahead in time

### ISSUE THREAD

**Issue by oniX0n** [zzag/plasma5-wallpapers-dynamic#38]
It seems like my wallpaper is ahead in time. It's getting dark about two hours before sunset at my actual location. Im in Germany. Now i just set my location further west, but i thought to report it would do no harm. 
Im using a wallpaper imported from a .heic file.

**Comment by zzag** [comment]
Does your wallpaper contain solar metadata?

**Comment by oniX0n** [comment]
No it does not.

**Comment by zzag** [comment]
In that case, it's expected behavior because this plugin will do its sunrise/sunset magic only when the wallpaper comes with solar metadata.

**Comment by oniX0n** [comment]
Thanks!

**Comment by zzag** [comment]
I suggest to add some solar metadata that works best for your location or just find another wallpaper.
