### ISSUE TITLE
Cannot read .heic files "/wallpaper.heic is not a dynamic wallpaper."

### ISSUE THREAD

**Issue by bingulo** [zzag/plasma5-wallpapers-dynamic#43]
After de 3.0 release, that includes HEIF format for the dynamic wallpapers, I can't set any .heic wallpaper for my desktop, cause it isn't recognized as a dynamic wallpaper.
I'm using Archlinux with the KDE desktop environment. 
Thanks in advance!

**Comment by BruceZhang1993** [comment]
Same here. KDE on Arch Linux.

**Comment by zzag** [comment]
Did you use the kdynamicwallpaperbuilder tool to create that wallpaper.heic file?

**Comment by Shatur95** [comment]
Same here, but I downloaded `.heic` files from [dynamicwallpaper.club](https://www.dynamicwallpaper.club/gallery).

**Comment by zzag** [comment]
Dynamic wallpapers for macOS and this plugin are incompatible. However, it's possible to write a (Python) script that populates a heic file with metadata that is necessary for this plugin to function as desired. See src/lib/metadata.xml and src/lib/kdynamicwallpapermetadata.cpp for more details.

**Comment by Dkoeddnsnp** [comment]
I would be convenient to have 100% compatibility of this plugin and macos version.

**Comment by bingulo** [comment]
> Dynamic wallpapers for macOS and this plugin are incompatible. However, it's possible to write a (Python) script that populates a heic file with metadata that is necessary for this plugin to function as desired. See src/lib/metadata.xml and src/lib/kdynamicwallpapermetadata.cpp for more details.

Now I understand! Thank's for the explanation.

**Comment by zzag** [comment]
See https://github.com/zzag/plasma5-wallpapers-dynamic/commit/7c1150c257a63fd1afee3f51c88397952702155b

**Comment by Shatur95** [comment]
Thank you a lot, the solution worked perfectly.
But is there any sense to use `.heic` if it does not compatible with MacOS format? Maybe use another format name to avoid confusing?
In previous versions, the .json format was quite convenient.
