### ISSUE TITLE
"File not found" whilst using kdynamicwallpaperbuilder

### ISSUE THREAD

**Issue by AquaticFish** [zzag/plasma5-wallpapers-dynamic#45]
Can't seem to get it to work, it just says "file not found".
![Screenshot_20200621_114254](https://user-images.githubusercontent.com/45541485/85220488-7cf2e600-b3b4-11ea-97b1-f44fc954c147.png)

**Comment by zzag** [comment]
Can I have a look at the metadata json file?

**Comment by AquaticFish** [comment]
Here you go, the previous one included with the "wallpaper package" didn't work so I wrote my own based on your guide.
`[
    {
        "Time": "00:00",
        "FileName": "dear-1.jpg"
    },
    {
        "Time": "02:00",
        "FileName": "dear-2.jpg"
    },
    {
        "Time": "04:00",
        "FileName": "dear-3.jpg"
    },
    {
        "Time": "06:00",
        "FileName": "dear-4.jpg"
    },
    {
        "Time": "08:00",
        "FileName": "dear-5.jpg"
    },
    {
        "Time": "10:00",
        "FileName": "dear-6.jpg"
    },
    {
        "Time": "12:00",
        "FileName": "dear-7.jpg"
    },
    {
        "Time": "14:00",
        "FileName": "dear-8.jpg"
    },
    {
        "Time": "16:00",
        "FileName": "dear-9.jpg"
    },
    {
        "Time": "18:00",
        "FileName": "dear-10.jpg"
    },
    {
        "Time": "20:00",
        "FileName": "dear-11.jpg"
    },
    {
        "Time": "22:00",
        "FileName": "dear-12.jpg"
    }
]`

**Comment by zzag** [comment]
The FileName field indicates the file path of an image relative to the metadata json file. It's also possible to specify the absolute file path.

**Comment by zzag** [comment]
"FileName" was probably a bad choice.

**Comment by zzag** [comment]
Anyway, I believe that you will be able to build the wallpaper successfully after moving images to the directory where the metadata json file is located.

**Comment by AquaticFish** [comment]
Thank you, it worked.
