### ISSUE TITLE
Calculate sun position automatically

### ISSUE THREAD

**Issue by l0drex** [zzag/plasma5-wallpapers-dynamic#46]
It would be nice if the sun position could be automatically calculated using GPS coordinates and the time / date the photo was taken.
This would also help to add support for wallpapers from https://dynamicwallpaper.club/ in the future (which would be awesome :smile:).

**Comment by zzag** [comment]
> It would be nice if the sun position could be automatically calculated using GPS coordinates and the time / date the photo was taken.

This should be do-able in general. Just read EXIF metadata and then use `KSunPosition` to get the position of the Sun. I wonder if KDE has something for reading EXIF metadata.
