### ISSUE TITLE
"JSON document is empty" while using kdynamicwallpaperbuilder

### ISSUE THREAD

**Issue by pranavtifr** [zzag/plasma5-wallpapers-dynamic#47]
I can't seem to get it to work. I tried keeping it in the same folder as images and everything. 
I have attached the relevant JSON document.

[metadata.json](https://github.com/zzag/plasma5-wallpapers-dynamic/files/4840963/metadata.log)

If it is any help, I am able to read the json document using pandas in python.

`

**Comment by thblckjkr** [comment]
I had the same problem, long story short, the document schema changed.

You need to take out the `MetaData` property to the root level

Somethig like this
```json
# metadata.json
[
    {
                "Time": 0,
                "FileName": "dear-1.jpg"
    },
    { 
        // The rest of the elements
    }
]
```

**Comment by pranavtifr** [comment]
Thanks a lot. I have a few followup issues though. If i just take `MetaData` property to root level, I get the error, `Time must be a String`. Putting time under quotes, gives the error, `Failed to parse Time`.

**Comment by thblckjkr** [comment]
Oh yeah, completely forgot about that.

Time needs to be in `hh:mm` format.

**Comment by pranavtifr** [comment]
Thanks a lot. This worked.

**Comment by zzag** [comment]
> Time needs to be in `hh:mm` format.

Yeah, I had received a couple of complaints about specifying the time as a real number between 0 and 1, so I've changed that in v3.
