### ISSUE TITLE
heic-file is not a dynamic wallpaper

### ISSUE THREAD

**Issue by somniumAeternam** [zzag/plasma5-wallpapers-dynamic#50]
I built and installed this program on my system and tried to import the new macOS Big Sur dynamic wallpapers. But this is not working. On the screen there is only an error message, that this file is not a dynamic wallpaper. Do I need to adapt these heic-files?

**Comment by zzag** [comment]
Dynamic wallpapers for macOS and this plugin are incompatible. Please keep this issue open because I've started receiving quite a lot of similar issues. See also #43.

**Comment by zzag** [comment]
I've just had a look at pyheif and it seems like it allows to load only the primary image. :(
