### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by SachinMaharana** [zzag/plasma5-wallpapers-dynamic#51]
I am getting the following error 

```
cmake .. -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_TESTING=OFF
CMake Error at CMakeLists.txt:11 (find_package):
  Could not find a configuration file for package "ECM" that is compatible
  with requested version "5.66.0".

  The following configuration files were considered but not accepted:

    /usr/share/ECM/cmake/ECMConfig.cmake, version: 5.44.0
```

uname -a                                                                                        1 ↵
Linux legion 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zzag** [comment]
This wallpaper plugin needs KF >= 5.66, your distro ships 5.44. If you don't want to upgrade your distro, kubuntu-backports is a good alternative way to get the latest KF.

**Comment by SachinMaharana** [comment]
Thanks. I did search about kubuntu-backports but couldn't find any helpful article on it. Any help in link to do this?

**Comment by zzag** [comment]
From https://launchpad.net/~kubuntu-ppa/+archive/ubuntu/backports

```
sudo add-apt-repository ppa:kubuntu-ppa/backports
sudo apt-get update
```

**Comment by zzag** [comment]
Although, it looks like kubuntu-backports ships only KF 5.47.

**Comment by zzag** [comment]
Unfortunately, I don't see any viable option other than upgrading your distro. Alternatively, you could switch to a distro that ships more "fresher" software, e.g. openSUSE Tumbleweed or KDE neon (it's basically lts ubuntu + latest kde plasma).
