### ISSUE TITLE
Im facing this error on Kubuntu 20.04

### ISSUE THREAD

**Issue by federicosnobohm** [zzag/plasma5-wallpapers-dynamic#53]
federico@Kubuntu:~/plasma5-wallpapers-dynamic/build$ make
[  7%] Built target com.github.zzag.dynamic-wallpapers-metadata-json
[  7%] Automatic MOC for target kdynamicwallpaper
[  7%] Built target kdynamicwallpaper_autogen
[  7%] Building CXX object src/lib/CMakeFiles/kdynamicwallpaper.dir/kdynamicwallpaperreader.cpp.o
/home/federico/plasma5-wallpapers-dynamic/src/lib/kdynamicwallpaperreader.cpp:12:10: fatal error: QColorSpace: No existe el archivo o el directorio
   12 | #include <QColorSpace>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/lib/CMakeFiles/kdynamicwallpaper.dir/build.make:108: src/lib/CMakeFiles/kdynamicwallpaper.dir/kdynamicwallpaperreader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:673: src/lib/CMakeFiles/kdynamicwallpaper.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
federico@Kubuntu:~/plasma5-wallpapers-dynamic/build$

**Comment by zzag** [comment]
Have you installed qtbase5-dev?

**Comment by zzag** [comment]
Also, what version of Qt is installed on your computer?

**Comment by zzag** [comment]
Can you please test ^^^?

**Comment by zzag** [comment]
@federicosnobohm please let me know if you need help with testing the fix

**Comment by mitchelloharawild** [comment]
Thanks for https://github.com/zzag/plasma5-wallpapers-dynamic/commit/90d0fbd7ccd4d6d7008d0bf136e7b696da0fa587, on a fresh installation of Kubuntu 20.04 I now get this error:

```
plasma5-wallpapers-dynamic/src/lib/kdynamicwallpaperwriter.cpp:240:18: error: invalid use of incomplete type ‘class QDebug’
```

Removing the warning which causes the above error allows the `make` to progress further, which then stops with these errors:

```
plasma5-wallpapers-dynamic/src/declarative/dynamicwallpaperdescription.h:38:40: error: field ‘m_metaData’ has incomplete type ‘QVector<KDynamicWallpaperMetaData>’
plasma5-wallpapers-dynamic/src/declarative/dynamicwallpaperdescription.h:39:19: error: field ‘m_imageUrls’ has incomplete type ‘QVector<QUrl>’
```

**Comment by zzag** [comment]
@mitchelloharawild can you please test ^^^ ?

**Comment by mitchelloharawild** [comment]
Thanks, this resolves the first error. I am now experiencing the second errors:
```
plasma5-wallpapers-dynamic/src/declarative/dynamicwallpaperdescription.h:38:40: error: field ‘m_metaData’ has incomplete type ‘QVector<KDynamicWallpaperMetaData>’
plasma5-wallpapers-dynamic/src/declarative/dynamicwallpaperdescription.h:39:19: error: field ‘m_imageUrls’ has incomplete type ‘QVector<QUrl>’
```

**Comment by zzag** [comment]
@mitchelloharawild ^^^

**Comment by mitchelloharawild** [comment]
More progress, but still errored:
```
plasma5-wallpapers-dynamic/src/declarative/dynamicwallpaperimagehandle.cpp:108:64: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
```

**Comment by zzag** [comment]
Argh, yeah, that's right, Qt::SkipEmptyParts was introduced in Qt 5.14.

**Comment by zzag** [comment]
^^^ (fingers crossed)

**Comment by mitchelloharawild** [comment]
Works well now, thanks again for your work!
