### ISSUE TITLE
I'm not able to set a wallpaper, it complains that it isn't a dynamic wallpaper

### ISSUE THREAD

**Issue by zugc22484** [zzag/plasma5-wallpapers-dynamic#56]
I have extracted the wallpaper i want from the apple HEIC and created my own, and the software complains that it isn't a dynamic wallpaper, even though i've just created it with the command line

[link to the zip with the images, json, and created heic](https://boy.soy/i/xvvf.zip)

**Comment by zzag** [comment]
The metadata file looks fine to me. Can I have the output of the kdynamicwallpaperbuilder command? You've most likely specified wrong image file path.

**Comment by zzag** [comment]
Ping. If you don't respond in a couple of days, I'll close this issue due to lack of activity.

**Comment by zzag** [comment]
Closing due to the lack of activity.
