### ISSUE TITLE
Additional wallpapers wiki page for v3.x

### ISSUE THREAD

**Issue by karmanyaahm** [zzag/plasma5-wallpapers-dynamic#57]
I have forked the Lakeside wallpaper and made a repo with the heic and have updated my own wallpaper as follows:

<https://github.com/karmanyaahm/plasma5-wallpapers-dynamic-spaceship-you-creative>
<https://github.com/karmanyaahm/dynamicwallpaper-lakeside-louis-coyle>

It would make it easier for users to find these and other wallpapers if the wiki page was created.

**Comment by zzag** [comment]
There was a wiki page for v2.x with additional wallpapers. I made it editable for all users. However, from time to time, people were adding dynamic wallpapers from macOS (catalina and mojave), which I had to remove quickly. With the release of v3.0, I restricted the editing rights.

If we need a place with a curated list of dynamic wallpapers, could it maybe be a separate repository? That way, we could have at least some sort of moderation.

**Comment by karmanyaahm** [comment]
I'll be happy to create/maintain such a repository probably called awesome-plasma5-dynamic-wallpapers. I'll fork it from one of the many `awesome-something` repositories and will share the created repository with you.

**Comment by zzag** [comment]
Thanks.

**Comment by karmanyaahm** [comment]
I have created the repo here <https://github.com/karmanyaahm/awesome-plasma5-dynamic-wallpapers>. Are there any changes that you think I should make to it?

**Comment by zzag** [comment]
> The wallpaper repo should link back to https://github.com/zzag/plasma5-wallpapers-dynamic

uh, maybe https://github.com/karmanyaahm/awesome-plasma5-dynamic-wallpapers?

**Comment by karmanyaahm** [comment]
I implemented that to make sure that if someone finds a wallpaper without the list, they can easily find the software they need to use that wallpaper.

**Comment by zzag** [comment]
Okay, fair enough.

**Comment by karmanyaahm** [comment]
Is it possible for you to refer to the list perhaps in the readme or wiki of this repo so it can get more exposure by both users and wallpaper designers?

**Comment by zzag** [comment]
Will do, but it will be much faster if you create a merge request. ;-)

Also, thank you very much for being generous enough to create the list and
willing to maintain it.
