### ISSUE TITLE
Italian translation filename (it-IT.po) is incorrect

### ISSUE THREAD

**Issue by eeickmeyer** [zzag/plasma5-wallpapers-dynamic#60]
Hi there,

I have finished packaging plasma5-wallpapers-dynamic for Ubuntu. I ran into one issue: the Itialian translation name (it-IT.po) is incorrect and should simply be it.po. It was rather easy to patch, so attached is the patch I created (though it might be easier for you to simply rename it). Without this fix, lintian gave me a pretty sizable headache. :)

I'll probably package this for Fedora fairly soon as well, but I thought I'd at least make you aware of this issue.

[0001-Fix-translation-filename.patch.txt](https://github.com/zzag/plasma5-wallpapers-dynamic/files/5023284/0001-Fix-translation-filename.patch.txt)

**Comment by zzag** [comment]
Thank you for reporting this issue. Can you please create a merge request? :-)

**Comment by eeickmeyer** [comment]
Done.

**Comment by zzag** [comment]
> I have finished packaging plasma5-wallpapers-dynamic for Ubuntu.

@eeickmeyer  Also, I should have mentioned that "plasma5-wallpapers-dynamic" follows Arch Linux package naming conventions. If it is a really bad package name according to Ubuntu/Debian conventions, please change it. It seems like "plasma-wallpaper-dynamic" is a better choice.
