### ISSUE TITLE
Cant install on Kubuntu 20.04

### ISSUE THREAD

**Issue by federicosnobohm** [zzag/plasma5-wallpapers-dynamic#63]
cant install

federico@Kubuntu:~/Descargas/plasma5-wallpapers-dynamic-3.3.4/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/federico/Descargas/plasma5-wallpapers-dynamic-3.3.4/build/CMakeFiles/CMakeOutput.log".
See also "/home/federico/Descargas/plasma5-wallpapers-dynamic-3.3.4/build/CMakeFiles/CMakeError.log".

**Comment by zzag** [comment]
You don't have a C++ compiler installed. Does installing `build-essential` package help?

**Comment by federicosnobohm** [comment]
Yes now is working pretty good! that was the error! great job changing to .heic estension, now we can install a lot of walls from mac os.

**Comment by zzag** [comment]
Thanks.
