### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by federicos1985** [zzag/plasma5-wallpapers-dynamic#65]
i have a issue installing this plugin, iam on mx linux kde plasma.

CMake Error at CMakeLists.txt:11 (find_package):
  Could not find a configuration file for package "ECM" that is compatible
  with requested version "5.66.0".

  The following configuration files were considered but not accepted:

    /usr/share/ECM/cmake/ECMConfig.cmake, version: 5.54.0

-- Configuring incomplete, errors occurred!

**Comment by zzag** [comment]
You have a little bit outdated KDE Frameworks on your computer, 5.54 was released almost two years ago. This wallpaper needs 5.66 or later.
