### ISSUE TITLE
Dynamic not listed

### ISSUE THREAD

**Issue by TommysG** [zzag/plasma5-wallpapers-dynamic#69]
Any idea why dynamic is not listed on "Configure Desktop"? I followed the steps step by step. My Linux distro is Manjaro.

**Comment by zzag** [comment]
Did you install the AUR package?

**Comment by TommysG** [comment]
Yes, I did all the steps. No error while building. kdynamicwallpaperbuilder command works fine from the terminal, but no Dynamic selection listed on wallpapers plugin.

**Comment by zzag** [comment]
Weird. Just to be sure, you don't see "Dynamic" under "Wallpaper Type:" combobox, right?

**Comment by TommysG** [comment]
Yes exactly, only the KDE defaults are listed. But it worked with other packages I tried. Very weird.

**Comment by zzag** [comment]
Do you use `yay`? Can I also have the output of `qtpaths --plugin-dir`?

**Comment by TommysG** [comment]
Yes i used `yay`. Yes of course.

```
qtpaths --plugin-dir                                              
/usr/lib/qt/plugins
```
This is what i get from this command. I also tried the steps with git, but no luck.

**Comment by zzag** [comment]
Do you have Anaconda installed on your computer by any chance?

**Comment by zzag** [comment]
@TommysG Can you please respond to my last comment? otherwise I'll close this issue due to the lack of activity.

**Comment by TommysG** [comment]
Yeah sorry i solved id. I upgraded some packages reinstall it and then it showed up. Thanks for the help!

**Comment by zzag** [comment]
Okay, thanks for the heads-up. :)
