### ISSUE TITLE
Bad convertation

### ISSUE THREAD

**Issue by Akergez** [zzag/plasma5-wallpapers-dynamic#71]
i converted .heic wallpaper from MacOS but converted wallpaper is broken
![2021-01-31_13-36](https://user-images.githubusercontent.com/78296459/106378828-9a1b7880-63c9-11eb-93e4-0b6b8a8362c2.png)

**Comment by zzag** [comment]
Could you please provide more details? It's not exactly clear what the issue is.

**Comment by Akergez** [comment]
> Could you please provide more details? It's not exactly clear what the issue is.

Strange artifacts. I thought that it happends because wrong convertation, but when i use a standart wallpaper with clock, i got the same problem
![2021-01-31_21-12](https://user-images.githubusercontent.com/78296459/106390329-ade6cf00-6409-11eb-9470-a826850c5566.png)
![2021-01-31_21-13](https://user-images.githubusercontent.com/78296459/106390330-b0492900-6409-11eb-964b-f41eeca6cb93.png)

**Comment by Akergez** [comment]
> Could you please provide more details? It's not exactly clear what the issue is.

**Comment by zzag** [comment]
The visual "artifacts" that you see are caused by cross-fading between images in the desktop wallpaper. If you don't want the images in the dynamic wallpaper to be cross-faded, don't pass the `--crossfade` option to the converter script. I hope that helps. :)
