### ISSUE TITLE
Please support for OpenSuse

### ISSUE THREAD

**Issue by God-Kazuma** [zzag/plasma5-wallpapers-dynamic#76]
Use an OBS repository previously, but this does not work well today on my computer, I can't add the dynamic wallpapers.
By compiling the Git program I give the following error because of the KF5 dependency:

- Could not find kf5config (missing: kf5config_dir)
- Could not find Kf5config: Found Neither Kf5Configconfig.cmake NOR KF5CONFIG-CONFIG.CMAKE
- Could not find kf5i18n (missing: kf5i18n_dir)
- Could Not Find Kf5i18n: Found Neither Kf5i18nconfig.cmake NOR KF5I18N-CONFIG.CMAKE
- Could not find kf5package (missing: kf5package_dir)
- Could not find Kf5Package: Found Neither Kf5PackageConfig.cmake NOR KF5PACKAGE-CONFIG.CMAKE
- Could not find kf5plasma (missing: kf5plasma_dir)
- Could Not Find Kf5Plasma: Found Neither Kf5Plasmaconfig.cmake Nor Kf5Plasma-Config.cmake
Cmake error at /usr/share/cmake/modules/findpackagehandlestandardargs.cmake :230 (Message):
  Could Not Find KF5 (Missing: Config i18n Package Plasma) (Required is at
  LEAST VERSION "5.66.0")
CALL STACK (MOST RECENT CALL FIRST):
  /usr/share/cmake/modules/findpackagehandlestandardargs.cmake :594 (_fphsa_failure_message)
  /usr/share/ecm/find-modules/findkf5.cmake :94 (find_package_handle_standard_args)
  Cmakelists.txt: 44 (find_package)

I really like your work, I would like to be able to continue using Dynamic Wallpaper 

Ps: Sorry for my english

**Comment by zzag** [comment]
It looks like you need to install some dev packages first. As for the OBS repository, I do not maintain it.
