### ISSUE TITLE
Library not added to path in Fedora

### ISSUE THREAD

**Issue by chase9** [zzag/plasma5-wallpapers-dynamic#77]
I just installed this on my machine and found that nothing worked. My tip off was this:
```
❯ kdynamicwallpaperbuilder
kdynamicwallpaperbuilder: error while loading shared libraries: libkdynamicwallpaper.so.1: cannot open shared object file: No such file or directory
```

I found that the library was present in /usr/lib, but that wasn't found in LD_LIBRARY_PATH. This variable actually wasn't present on my system, so I'm unsure if it's a problem with my machine or perhaps newer versions of Fedora have changed up how libraries are indexed?

In any case, the issue was fixed by running:
```
export LD_LIBRARY_PATH=/usr/lib
```

and now everything works! Thank you for the great plugin.

**Comment by zzag** [comment]
Interesting... Can you please check whether the plugin works out of the box if you build it without `-DCMAKE_INSTALL_LIBDIR=lib`?

**Comment by chase9** [comment]
I went through the process a few times and it works with and without that flag now. Maybe there was a pending update that messed with my library path? Not sure but thanks for looking at this issue anyways!
