### ISSUE TITLE
Available in Fedora

### ISSUE THREAD

**Issue by Enchufa2** [zzag/plasma5-wallpapers-dynamic#78]
FYI, I added this to the [RPM Fusion Free](https://rpmfusion.org/) repo for Fedora (see [here](https://admin.rpmfusion.org/pkgdb/package/free/plasma-wallpapers-dynamic/)), just in case you'd like to advertise it in the README. I changed the name a little bit (dropped the "5") to match our packaging guidelines, and it's divided in the following subpackages:

- plasma-wallpapers-dynamic
- plasma-wallpapers-dynamic-builder
- plasma-wallpapers-dynamic-builder-bash-completion
- plasma-wallpapers-dynamic-builder-fish-completion
- plasma-wallpapers-dynamic-builder-zsh-completion
- plasma-wallpapers-dynamic-devel

I built the package just yesterday, so it's in updates-testing. It will take a few days until it's available in the main updates repo.

**Comment by zzag** [comment]
Amazing, thanks. I'll add a relevant note about it in README file. :)
