### ISSUE TITLE
Cannot import .heic files

### ISSUE THREAD

**Issue by Dargh-Lenoule** [zzag/plasma5-wallpapers-dynamic#79]
so uh, i downloaded some wallpapers form https://dynamicwallpaper.club/gallery
and apparently, neither of those .heic files can be imported, because, whenever i do, it says that the file is not a dynamic wallpaper
and so yeah... I kinda have no idea, i just wanna have some dynamic wallpapers :'(
![image](https://user-images.githubusercontent.com/73076596/131262263-acaa28f7-8105-4855-8b93-5158f4e4b3da.png)
[Minimal Forest [FIXED].zip](https://github.com/zzag/plasma5-wallpapers-dynamic/files/7073065/Minimal.Forest.FIXED.zip)

**Comment by zzag** [comment]
Did you convert the dynamic wallpaper so it can be used by this engine? Please check README.md

**Comment by Dargh-Lenoule** [comment]
oh sorry, i think i missed it, i'll go fix it now

**Comment by zzag** [comment]
Is the issue resolved?

**Comment by zzag** [comment]
It's been a month since last comment. Closing this issue due to the lack of activity.
