### ISSUE TITLE
AVIF support using libavif?

### ISSUE THREAD

**Issue by Conan-Kudo** [zzag/plasma5-wallpapers-dynamic#87]
This plugin currently depends on libheif, which we cannot currently bring into Fedora. Would it be possible to change this to use libavif instead (which we do have in Fedora)?

This would allow us to bring this plugin into Fedora itself and use it in the KDE spin for our default wallpaper, which has come with animated flavors for a long time on GNOME, but hasn't been available on Plasma in that form.

**Comment by zzag** [comment]
I gave libavif a try, but there are severe performance issues and metadata handling issues. Both issues are fixable but not trivial and it can be a reason to bump the major version again.

**Comment by zzag** [comment]
> but there are severe performance issues and metadata handling issues

Addressed. Also, now, the plugin loads wallpapers faster with libavif than with libheif.

**Comment by Conan-Kudo** [comment]
Woot!
